#!/usr/bin/env bash
# shell.sh — pretty, fast zsh prompt. Idempotent.
# No sudo, no Homebrew. Writes only to ~/.local, ~/.config/starship.toml,
# ~/Library/Fonts, and ~/.zshrc.
# Exit 0 = done. Exit 1 = human action needed (message explains); re-run after.
set -euo pipefail

LOCAL="$HOME/.local"; BIN="$LOCAL/bin"; SHARE="$LOCAL/share/zsh/plugins"
mkdir -p "$BIN" "$SHARE" "$HOME/.config"

# 1. Starship prompt → ~/.local/bin/starship
if command -v starship >/dev/null 2>&1 || [ -x "$BIN/starship" ]; then
  echo "✓ starship already present"
else
  case "$(uname -m)" in arm64) SARCH="aarch64-apple-darwin";; *) SARCH="x86_64-apple-darwin";; esac
  URL="https://github.com/starship/starship/releases/latest/download/starship-${SARCH}.tar.gz"
  echo "… downloading starship-${SARCH}.tar.gz"
  curl -fsSL "$URL" -o /tmp/starship.tgz
  tar -xzf /tmp/starship.tgz -C "$BIN" starship
  chmod +x "$BIN/starship"
  echo "✓ starship $("$BIN/starship" --version | head -1 | awk '{print $2}')"
fi

# 2. JetBrainsMono Nerd Font → ~/Library/Fonts (user-level, no sudo)
if ls "$HOME/Library/Fonts" 2>/dev/null | grep -qi "JetBrainsMonoNerdFont"; then
  echo "✓ JetBrainsMono Nerd Font already installed"
else
  URL="https://github.com/ryanoasis/nerd-fonts/releases/latest/download/JetBrainsMono.zip"
  echo "… downloading JetBrainsMono Nerd Font"
  curl -fsSL "$URL" -o /tmp/jbm-nerd.zip
  rm -rf /tmp/jbm-nerd; mkdir -p /tmp/jbm-nerd
  unzip -q /tmp/jbm-nerd.zip -d /tmp/jbm-nerd
  mkdir -p "$HOME/Library/Fonts"
  cp /tmp/jbm-nerd/*.ttf "$HOME/Library/Fonts/" 2>/dev/null || true
  echo "✓ JetBrainsMono Nerd Font installed"
  echo "  → set it in Terminal.app: Preferences ▸ Profiles ▸ [your profile] ▸ Font ▸ Change,"
  echo "    pick \"JetBrainsMono Nerd Font\" (or any \"...Nerd Font Mono\" variant)."
fi

# 3. zsh-autosuggestions + zsh-syntax-highlighting → ~/.local/share/zsh/plugins
if [ -d "$SHARE/zsh-autosuggestions" ]; then
  echo "✓ zsh-autosuggestions already present"
else
  git clone -q --depth 1 https://github.com/zsh-users/zsh-autosuggestions "$SHARE/zsh-autosuggestions"
  echo "✓ zsh-autosuggestions installed"
fi

if [ -d "$SHARE/zsh-syntax-highlighting" ]; then
  echo "✓ zsh-syntax-highlighting already present"
else
  git clone -q --depth 1 https://github.com/zsh-users/zsh-syntax-highlighting "$SHARE/zsh-syntax-highlighting"
  echo "✓ zsh-syntax-highlighting installed"
fi

# 4. starship.toml — git status + GitHub icon, only written if absent (never overwrite edits)
#    Icon code points used below (all verified present via
#    https://github.com/ryanoasis/nerd-fonts/wiki/Glyph-Sets-and-Code-Points):
#      U+E0B0 — Powerline separator triangle (Powerline set, e0a0-e0a2/e0b0-e0b3, always bundled)
#      U+E709 — GitHub mark (Devicons set, e700-e8ef)
#      U+E725 — git-branch (Devicons set, e700-e8ef)
#    Do NOT use Font Awesome's old "github" glyph (historically U+F09B) — FA brand icons were
#    dropped from Nerd Fonts (the ed00-f2ff range ships "with two gaps"), so it renders as nothing.
#    Private-Use-Area glyphs typed directly into a shell/editor session can silently vanish in
#    some text pipelines; if you're hand-editing this, build them from verified code points via
#    `python3 -c "print(chr(0xE709))"` rather than pasting the character.
CONFIG="$HOME/.config/starship.toml"
if [ -f "$CONFIG" ]; then
  echo "✓ ~/.config/starship.toml already exists (not overwritten)"
else
  cat > "$CONFIG" <<'EOF'
# starship.toml — generated by dotfiles/bootstrap/shell.sh
"$schema" = 'https://starship.rs/config-schema.json'

format = """
$directory[](fg:#89b4fa bg:#a6e3a1)\
${custom.github}$git_branch$git_status[](fg:#a6e3a1)
$character"""

add_newline = true

[directory]
style = "bg:#89b4fa fg:#1e1e2e bold"
format = "[ $path ]($style)"
truncation_length = 3
truncate_to_repo = true

[custom.github]
command = "git config --get remote.origin.url 2>/dev/null | sed -E 's#\\.git$##; s#.*[:/]([^/]+/[^/]+)$#\\1#'"
when = "git remote get-url origin 2>/dev/null | grep -q github.com"
symbol = ""
style = "bg:#a6e3a1 fg:#1e1e2e bold"
format = "[ $symbol $output]($style)"
shell = ["bash", "--noprofile", "--norc"]

[git_branch]
symbol = " "
style = "bg:#a6e3a1 fg:#1e1e2e bold"
format = "[ $symbol$branch]($style)"

[git_status]
style = "bg:#a6e3a1 fg:#1e1e2e bold"
format = "[$all_status$ahead_behind ]($style)"
conflicted = "🏳"
ahead = "⇡${count}"
behind = "⇣${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
untracked = "?${count}"
stashed = "\\$${count}"
modified = "!${count}"
staged = "+${count}"
renamed = "»${count}"
deleted = "✘${count}"

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"

[cmd_duration]
format = "took [$duration]($style) "
style = "yellow"
EOF
  echo "✓ ~/.config/starship.toml written"
fi

# 5. Wire into ~/.zshrc (idempotent — one guarded block)
ZSHRC="$HOME/.zshrc"
touch "$ZSHRC"
if ! grep -qs '# >>> dotfiles shell.sh >>>' "$ZSHRC"; then
  cat >> "$ZSHRC" <<EOF

# >>> dotfiles shell.sh >>>
export PATH="\$HOME/.local/bin:\$PATH"
source "$SHARE/zsh-autosuggestions/zsh-autosuggestions.zsh"
eval "\$(starship init zsh)"
source "$SHARE/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"  # must load last
# <<< dotfiles shell.sh <<<
EOF
  echo "✓ ~/.zshrc wired (prompt + plugins)"
else
  echo "✓ ~/.zshrc already wired"
fi

echo
echo "Shell ready. Two things left, both manual/GUI (can't be scripted):"
echo "  1. Terminal.app ▸ Preferences ▸ Profiles ▸ [your profile] ▸ Font ▸ Change → pick a \"...Nerd Font\" variant."
echo "  2. Open a NEW terminal tab/window (or run: exec zsh) to load the new prompt."
